### ISSUE TITLE
Feature: User can browse card sets

### ISSUE THREAD

**Issue by tam-n** [tam-n/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can browse Pokemon TCG sets and cards within the collection

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can browse Pokemon TCG sets in an expansion series to view a collection of cards within the set. The user will be able to click on cards images within the collection to view information in an expanded image of the card.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/tam-n/ajax-project/assets/131913803/310ff91f-c57d-40d6-8bf5-156d6405e3a3)
![image](https://github.com/tam-n/ajax-project/assets/131913803/d9abe420-e852-43a6-b22d-0a4bc3d0638f)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Within the HTML header element, create the navigation bar so that it matches the Figma
  - [x] Create a hamburger menu that will display Home and My Deck menu when clicked
- [x] Create the layout of the Home Page with HTML and CSS utilizing flexbox
  - [x] Use CSS to design for mobile first
- [x] Create a collapsible section that will display the sets in an expansion series when clicked
  - [x] Make an XMLHTTP request to fetch all sets for each series
  - [x] Generate a DOM tree:
    - [x] Create a `img` element object and assign the attribute `data-view-id` the value of the card sets' id property.
    - [x] Create a `div` element object and set the `.textContent` to the name of the card sets' name property.
  - [x] Append the DOM tree to the matching collapsible for each card series
- [x] Create a function called `renderPokemonCards` with a parameter `setId` that does that following:
  - [x]  Makes an HTTP request for a set id that was passed as the argument
  - [x] For each card create an `img` element and append it to the appropriate HTML element to display the card images
- [x] Create a function `viewSwap` that does the following:
  - [x] Displays the card collection within a set when the set's image is clicked and called the `renderPokemonCard` function
  - [x] Swaps view to the home page when Home in the navigation bar is clicked
- [x] Add an event listener that will display an enlarged image of the card that is clicked as shown in the Figma.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
