### ISSUE TITLE
Feature: User can add cards into their deck

### ISSUE THREAD

**Issue by tam-n** [tam-n/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add cards into their deck.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can click on a card in a card collection of a set to display an enlarged version of the card. The user will be able to click on the add icon to add a card to their deck.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/tam-n/PokeDeck-Builder/assets/131913803/2b3f625c-ab4b-4189-bd31-9921d082759c)
![image](https://github.com/tam-n/PokeDeck-Builder/assets/131913803/86d4098e-ed5e-4c58-85ca-aa03d7186aeb)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Use plus font-awesome icons to be used as an add button
- [x] Add an event listener to the plus icon that:
  - [x] listens for the `click` event
  - [x] creates an object
  - [x] uses a conditional to check if the selected card's id exists in `data.myDeck`
   - [x] if it does not, add a `counter` property with a value of `1` to the object and add an `img` property with a value of the selected card's `src` attribute
   - [x] if it exists, increment the `counter` property
- [x] Create a function `toggleAddMinusButtons` that toggles the display of add button between hide and flex
- [x] Call `toggleAddMinusButtons` when a card is selected and when the user goes to the home page
- [x] In `data.js` add a `beforeunload` event listener to the `window` object that serializes the data model as JSON and stores the JSON in `localStorage`
- [x] Add a conditional to `data.js` that:
  - [x] Checks to see if there is a JSON data model stored in `localStorage`
  - [x] If there is, parse it and assign it to the initial `data` variable
- [x] Check to see if `data` was stored into `localStorage`
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
