### ISSUE TITLE
Feature: User can view their deck

### ISSUE THREAD

**Issue by tam-n** [tam-n/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their deck.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

While viewing a card set's collection the user can click on the My Deck tab to switch views to their deck on mobile. On desktop the user can see their deck side by side with the card collection, which updates live while cards are added to the deck. The user can also go to the navigation bar to view their deck in a bigger format.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/tam-n/PokeDeck-Builder/assets/131913803/fcbd2a6b-ca80-4bdb-841d-ebd35e958cf2)
![image](https://github.com/tam-n/PokeDeck-Builder/assets/131913803/d82b2b51-b231-4c72-98f9-ca1a5138a0a7)
![image](https://github.com/tam-n/PokeDeck-Builder/assets/131913803/3ae99b46-088b-44ac-ab0f-edb23e2b069d)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a function that renders the cards in `data.myDeck` when called, making sure cards with more than one `counter` are rendered multiple times
- [x] Create a function to clear the rendered deck from the DOM
- [x] Clear the deck when a set set a selected and render the deck whenever a set is selected 
- [x] Add a conditional that removes the "No Cards in Deck" `textContent` of the deck when the deck has at least one card.
  - [x] Display the first image in the deck as the cover image for the deck.
- [x] Add an event listener to display the cards in the deck when they are clicked
- [x] Create a `view-my-deck` and add an event listener that swaps view to `view-my-deck` whenever My Deck in the navigation bar is selected
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
