### ISSUE TITLE
Feature: User can delete cards in their deck

### ISSUE THREAD

**Issue by tam-n** [tam-n/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user can delete cards in their deck

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can press a minus button to delete a card from their deck. When there are no cards in the deck, a message will display "No Cards in Deck".

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/tam-n/PokeDeck-Builder/assets/131913803/56a112fd-88fa-4b1a-97b1-f872edbe93a9)
![image](https://github.com/tam-n/PokeDeck-Builder/assets/131913803/77791402-0677-4609-b999-40dd445a537c)
![image](https://github.com/tam-n/PokeDeck-Builder/assets/131913803/b5267f9a-3789-42e5-b407-0b18faecd61a)
![image](https://github.com/tam-n/PokeDeck-Builder/assets/131913803/6a9fea62-731a-41b3-be56-db0b2801fd67)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add conditionals for when the card deck is 0 to toggle display "No Cards in Deck"
- [x] Add event listener for when the "minus" button is clicked to:
  - [x] remove one counter of displayed card's counter property in `data.myDeck`
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
