### ISSUE TITLE
Feature: User can clear an entire deck

### ISSUE THREAD

**Issue by tam-n** [tam-n/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user can clear the entire deck.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can use a button to clear the entire deck using a button in the My Deck. This allows for a quicker way to delete cards.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/tam-n/ajax-project/assets/131913803/840a0712-99bc-48ab-b7b4-bf6864c3358d)
![image](https://github.com/tam-n/ajax-project/assets/131913803/af05ea69-7eab-4e16-9b7a-03f79b548386)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x]  Create  a button and  use a `onclick` that will call a function when clicked
- [x] In main.js create a function that:
  - [x] clears the cards from the DOM tree
  - [x] sets my `data.myDeck` to an empty object literal.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
